#!/bin/bash

echo $(date)
# Create a `builder` user for makepkg
useradd --no-create-home --shell=/bin/bash builder && usermod -L builder
echo "builder ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
echo "root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
# Install dependencies
source /package/PKGBUILD || exit
pacman -Syu --noconfirm base-devel git sudo 
pacman -S --noconfirm --needed --asdeps "${makedepends[@]}" "${depends[@]}"
# Prepare build directory
cd /artifacts || exit
cp -r /package/* . || exit
# Needed to ensure PATH is properly set for perl, etc.
source /etc/profile || exit
# Finally build it
sudo -u builder BUILDDIR=/tmp makepkg -srci --noconfirm
