[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"

[aarchup]
source = "gitlab"
gitlab = "artafinde/aarchup"
use_max_tag = true

[cachyos-ananicy-rules]
source = "git"
git = "https://github.com/CachyOS/ananicy-rules.git"

[corefreq]
source = "github"
github = "cyring/CoreFreq"
use_latest_release = true

[droplet-agent]
source = "github"
github = "digitalocean/droplet-agent"
use_latest_tag = true

[intellij-idea-ua-eap]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='IntelliJ IDEA']/channel[@status='release' or @status='eap']/build/@fullNumber)\" -"

[intellij-idea-ce-eap]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='IntelliJ IDEA']/channel[@status='release' or @status='eap']/build/@fullNumber)\" -"

[linux-prjc]
source = "gitlab"
gitlab = "alfredchen/linux-prjc"
use_max_tag = true
prefix = "v"
