[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "apikey.crypt"

# Community #
[alot]
source = "github"
github = "pazz/alot"
use_max_tag = true

[neomutt]
source = "github"
github = "neomutt/neomutt"
use_max_tag = true

[makedumpfile]
source = "github"
github = "makedumpfile/makedumpfile"
use_max_tag = true

[memray]
source = "github"
github = "bloomberg/memray"
prefix = "v"
use_max_tag = true

[opensearch]
source = "github"
github = "opensearch-project/OpenSearch"
use_max_tag = true

[opensearch-alerting-plugin]
source = "github"
github = "opensearch-project/alerting"
use_latest_tag = true

[opensearch-anomaly-detection-plugin]
source = "github"
github = "opensearch-project/anomaly-detection"
use_latest_tag = true

[opensearch-asynchronous-search-plugin]
source = "github"
github = "opensearch-project/asynchronous-search"
use_latest_tag = true

[opensearch-cross-cluster-replication-plugin]
source = "github"
github = "opensearch-project/cross-cluster-replication"
use_latest_tag = true

[opensearch-dashboards]
source = "github"
github = "opensearch-project/opensearch-dashboards"
use_latest_tag = true

[opensearch-dashboards-alerting-plugin]
source = "github"
github = "opensearch-project/alerting-dashboards-plugin"
use_latest_tag = true

[opensearch-dashboards-anomaly-detection-plugin]
source = "github"
github = "opensearch-project/anomaly-detection-dashboards-plugin"
use_latest_tag = true

[opensearch-dashboards-gantt-chart-plugin]
source = "github"
github = "opensearch-project/dashboards-visualizations"
use_latest_tag = true

[opensearch-dashboards-index-management-plugin]
source = "github"
github = "opensearch-project/index-management-dashboards-plugin"
use_latest_tag = true

[opensearch-dashboards-observability-plugin]
source = "github"
github = "opensearch-project/observability"
use_latest_tag = true

[opensearch-dashboards-query-workbench-plugin]
source = "github"
github = "opensearch-project/sql"
use_latest_tag = true

[opensearch-dashboards-reports-plugin]
source = "github"
github = "opensearch-project/dashboards-reports"
use_latest_tag = true

[opensearch-dashboards-security-plugin]
source = "github"
github = "opensearch-project/security-dashboards-plugin"
use_latest_tag = true

[opensearch-index-management-plugin]
source = "github"
github = "opensearch-project/index-management"
use_latest_tag = true

[opensearch-job-scheduler-plugin]
source = "github"
github = "opensearch-project/job-scheduler"
use_latest_tag = true

[opensearch-knn-plugin]
source = "github"
github = "opensearch-project/k-NN"
use_latest_tag = true

[opensearch-observability-plugin]
source = "github"
github = "opensearch-project/observability"
use_latest_tag = true

[opensearch-performance-analyzer-plugin]
source = "github"
github = "opensearch-project/performance-analyzer"
use_latest_tag = true

[opensearch-reports-scheduler-plugin]
source = "github"
github = "opensearch-project/dashboards-reports"
use_latest_tag = true

[opensearch-security-plugin]
source = "github"
github = "opensearch-project/security"
use_latest_tag = true

[opensearch-sql-plugin]
source = "github"
github = "opensearch-project/sql"
use_max_tag = true
sort_version_key = "vercmp"

[python-mysql-connector]
source = "github"
github = "mysql/mysql-connector-python"
use_latest_tag = true

[freeplane]
source = "github"
github = "freeplane/freeplane"
use_max_tag = true
prefix = "release-"
exclude_regex = ".*pre.*"

[gdu]
source = "github"
github = "dundee/gdu"
use_max_tag = true

[shotcut]
source = "github"
github = "mltframework/shotcut"
use_max_tag = true
prefix = "v"
ignored = "v22.01.17 v22.03.06 v22.03.20"

[tectonic]
source = "github"
github = "tectonic-typesetting/tectonic"
use_max_tag = true
prefix = "tectonic@"
include_regex = "tectonic@.*"

[vulture]
source = "github"
github = "jendrikseipp/vulture"
use_max_tag = true
prefix = "v"

[liquidctl]
source = "github"
github = "liquidctl/liquidctl"
use_max_tag = true
prefix = "v"

[profile-sync-daemon]
source = "github"
github = "graysky2/profile-sync-daemon"
use_max_tag = true
prefix = "v"

[keycloak]
source = "github"
github = "keycloak/keycloak"
use_max_tag = true

[profile-cleaner]
source = "github"
github = "graysky2/profile-cleaner"
use_max_tag = true
prefix = "v"

[intellij-idea-community-edition]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='IntelliJ IDEA']/channel[@status='release' or @status!='eap']/build/@version)\" -"

[pycharm-community-edition]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='PyCharm']/channel[@status='release' or @status!='eap']/build/@version)\" -"

[jsoncpp]
source = "github"
github = "open-source-parsers/jsoncpp"
use_max_tag = true

[gitlab-exporter]
source = "git"
git = "https://gitlab.archlinux.org/artafinde/gitlab-exporter.git"
prefix = "v"

[polybar]
source = "github"
github = "polybar/polybar"
use_latest_tag = true

[prometheus-systemd-exporter]
source = "github"
github = "povilasv/systemd_exporter"
use_latest_tag = true
prefix = "v"

[keycloak-archlinux-theme]
source = "git"
git = "https://gitlab.archlinux.org/archlinux/keycloak-archlinux-theme.git"
prefix = "v"

[rustypaste-cli]
source = "github"
github = "orhun/rustypaste-cli"
use_max_tag = true
prefix = "v"

# AUR #
[aarchup]
source = "gitlab"
gitlab = "artafinde/aarchup"
use_max_tag = true

[caatinga]
source = "github"
github = "headmastersquall/caatinga"
use_max_tag = true
prefix = "caatinga-"

[corefreq]
source = "github"
github = "cyring/CoreFreq"
use_max_tag = true

[cpufreq]
source = "github"
github = "konkor/cpufreq"
use_max_tag = true

[lab-bin]
source = "github"
github = "zaquestion/lab"
use_max_tag = true

[topicons-redux]
source = "gitlab"
gitlab = "pop-planet/TopIcons-Redux"
use_max_tag = true

[intellij-idea-ua-eap]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='IntelliJ IDEA']/channel[@status='release' or @status='eap']/build/@fullNumber)\" -"

[intellij-idea-ce-eap]
source = "cmd"
cmd = "curl -s --location --header \"Accept: application/rdf+xml\" https://www.jetbrains.com/updates/updates.xml | xmllint --xpath \"string(/products/product[@name='IntelliJ IDEA']/channel[@status='release' or @status='eap']/build/@fullNumber)\" -"

[jd-gui]
source = "github"
github = "java-decompiler/jd-gui"
use_max_tag = true
prefix = "v"

[linux-prjc]
source = "gitlab"
gitlab = "alfredchen/linux-prjc"
use_max_tag = true
prefix = "v"

[python-prometheus-fastapi-instrumentator]
source = "github"
github = "trallnag/prometheus-fastapi-instrumentator"
use_max_tag = true
prefix = "v"

[python-sklearn-pandas]
source = "github"
github = "scikit-learn-contrib/sklearn-pandas"
use_max_tag = true
prefix = "v"
